export interface TableColumn {
  name: string;
  type: string;
  nullable: boolean;
}

export interface TableSchema {
  name: string;
  columns: TableColumn[];
  isView?: boolean;
}

export interface DatabaseSchema {
  tables: TableSchema[];
  views: TableSchema[];
  enums: { name: string; values: string[] }[];
}

// Pre-defined schema based on the Supabase types
export function getDatabaseSchema(): DatabaseSchema {
  return {
    tables: [
      {
        name: 'profiles',
        columns: [
          { name: 'id', type: 'uuid', nullable: false },
          { name: 'email', type: 'string', nullable: true },
          { name: 'full_name', type: 'string', nullable: true },
          { name: 'username', type: 'string', nullable: true },
          { name: 'phone', type: 'string', nullable: true },
          { name: 'avatar_url', type: 'string', nullable: true },
          { name: 'bio', type: 'string', nullable: true },
          { name: 'user_type', type: 'user_type', nullable: true },
          { name: 'business_category', type: 'string', nullable: true },
          { name: 'is_verified', type: 'boolean', nullable: true },
          { name: 'is_banned', type: 'boolean', nullable: true },
          { name: 'banned_at', type: 'timestamp', nullable: true },
          { name: 'banned_reason', type: 'string', nullable: true },
          { name: 'rating_avg', type: 'number', nullable: true },
          { name: 'rating_count', type: 'number', nullable: true },
          { name: 'location_city', type: 'string', nullable: true },
          { name: 'location_state', type: 'string', nullable: true },
          { name: 'location_lat', type: 'number', nullable: true },
          { name: 'location_lng', type: 'number', nullable: true },
          { name: 'language', type: 'string', nullable: true },
          { name: 'pinned_badges', type: 'string[]', nullable: true },
          { name: 'show_online_status', type: 'boolean', nullable: true },
          { name: 'show_phone_on_listings', type: 'boolean', nullable: true },
          { name: 'allow_messages_from_anyone', type: 'boolean', nullable: true },
          { name: 'website_url', type: 'string', nullable: true },
          { name: 'instagram_url', type: 'string', nullable: true },
          { name: 'whatsapp_number', type: 'string', nullable: true },
          { name: 'created_at', type: 'timestamp', nullable: true },
          { name: 'updated_at', type: 'timestamp', nullable: true },
        ],
      },
      {
        name: 'listings',
        columns: [
          { name: 'id', type: 'uuid', nullable: false },
          { name: 'owner_id', type: 'uuid', nullable: false },
          { name: 'type', type: 'listing_type', nullable: false },
          { name: 'status', type: 'listing_status', nullable: true },
          { name: 'title', type: 'string', nullable: false },
          { name: 'description', type: 'string', nullable: true },
          { name: 'price', type: 'number', nullable: true },
          { name: 'images', type: 'string[]', nullable: true },
          { name: 'is_negotiable', type: 'boolean', nullable: true },
          { name: 'is_premium', type: 'boolean', nullable: true },
          { name: 'is_sponsored', type: 'boolean', nullable: true },
          { name: 'sponsored_at', type: 'timestamp', nullable: true },
          { name: 'sponsored_by', type: 'string', nullable: true },
          { name: 'sponsored_until', type: 'timestamp', nullable: true },
          { name: 'location_city', type: 'string', nullable: true },
          { name: 'location_state', type: 'string', nullable: true },
          { name: 'location_lat', type: 'number', nullable: true },
          { name: 'location_lng', type: 'number', nullable: true },
          { name: 'last_bumped_at', type: 'timestamp', nullable: true },
          { name: 'expires_at', type: 'timestamp', nullable: true },
          { name: 'created_at', type: 'timestamp', nullable: true },
          { name: 'updated_at', type: 'timestamp', nullable: true },
        ],
      },
      {
        name: 'vehicle_attributes',
        columns: [
          { name: 'id', type: 'uuid', nullable: false },
          { name: 'listing_id', type: 'uuid', nullable: false },
          { name: 'make', type: 'string', nullable: true },
          { name: 'model', type: 'string', nullable: true },
          { name: 'year', type: 'number', nullable: true },
          { name: 'mileage', type: 'number', nullable: true },
          { name: 'vin', type: 'string', nullable: true },
          { name: 'fuel_type', type: 'string', nullable: true },
          { name: 'transmission', type: 'string', nullable: true },
          { name: 'color', type: 'string', nullable: true },
          { name: 'condition', type: 'vehicle_condition', nullable: true },
        ],
      },
      {
        name: 'part_attributes',
        columns: [
          { name: 'id', type: 'uuid', nullable: false },
          { name: 'listing_id', type: 'uuid', nullable: false },
          { name: 'part_category', type: 'string', nullable: true },
          { name: 'brand', type: 'string', nullable: true },
          { name: 'compatible_makes', type: 'string[]', nullable: true },
          { name: 'compatible_models', type: 'string[]', nullable: true },
          { name: 'compatible_years', type: 'int4range', nullable: true },
          { name: 'condition', type: 'vehicle_condition', nullable: true },
        ],
      },
      {
        name: 'service_attributes',
        columns: [
          { name: 'id', type: 'uuid', nullable: false },
          { name: 'listing_id', type: 'uuid', nullable: false },
          { name: 'service_category', type: 'service_category', nullable: true },
          { name: 'price_structure', type: 'string', nullable: true },
          { name: 'availability', type: 'string[]', nullable: true },
        ],
      },
      {
        name: 'conversations',
        columns: [
          { name: 'id', type: 'uuid', nullable: false },
          { name: 'listing_id', type: 'uuid', nullable: false },
          { name: 'seller_id', type: 'uuid', nullable: false },
          { name: 'buyer_id', type: 'uuid', nullable: false },
          { name: 'last_message_at', type: 'timestamp', nullable: true },
          { name: 'created_at', type: 'timestamp', nullable: false },
        ],
      },
      {
        name: 'messages',
        columns: [
          { name: 'id', type: 'uuid', nullable: false },
          { name: 'conversation_id', type: 'uuid', nullable: false },
          { name: 'sender_id', type: 'uuid', nullable: false },
          { name: 'content', type: 'string', nullable: false },
          { name: 'message_type', type: 'message_type', nullable: false },
          { name: 'media_url', type: 'string', nullable: true },
          { name: 'media_duration', type: 'number', nullable: true },
          { name: 'status', type: 'message_status', nullable: false },
          { name: 'created_at', type: 'timestamp', nullable: false },
        ],
      },
      {
        name: 'reviews',
        columns: [
          { name: 'id', type: 'uuid', nullable: false },
          { name: 'listing_id', type: 'uuid', nullable: false },
          { name: 'reviewer_id', type: 'uuid', nullable: false },
          { name: 'rating', type: 'number', nullable: false },
          { name: 'communication_rating', type: 'number', nullable: true },
          { name: 'accuracy_rating', type: 'number', nullable: true },
          { name: 'service_rating', type: 'number', nullable: true },
          { name: 'comment', type: 'string', nullable: true },
          { name: 'created_at', type: 'timestamp', nullable: true },
        ],
      },
      {
        name: 'favorites',
        columns: [
          { name: 'id', type: 'uuid', nullable: false },
          { name: 'user_id', type: 'uuid', nullable: false },
          { name: 'listing_id', type: 'uuid', nullable: false },
          { name: 'created_at', type: 'timestamp', nullable: true },
        ],
      },
      {
        name: 'user_badges',
        columns: [
          { name: 'id', type: 'uuid', nullable: false },
          { name: 'user_id', type: 'uuid', nullable: false },
          { name: 'badge_type', type: 'string', nullable: false },
          { name: 'badge_name', type: 'string', nullable: false },
          { name: 'badge_description', type: 'string', nullable: true },
          { name: 'badge_icon', type: 'string', nullable: true },
          { name: 'earned_at', type: 'timestamp', nullable: false },
        ],
      },
      {
        name: 'user_roles',
        columns: [
          { name: 'id', type: 'uuid', nullable: false },
          { name: 'user_id', type: 'uuid', nullable: false },
          { name: 'role', type: 'app_role', nullable: false },
          { name: 'created_at', type: 'timestamp', nullable: true },
        ],
      },
      {
        name: 'push_subscriptions',
        columns: [
          { name: 'id', type: 'uuid', nullable: false },
          { name: 'user_id', type: 'uuid', nullable: false },
          { name: 'endpoint', type: 'string', nullable: false },
          { name: 'p256dh', type: 'string', nullable: false },
          { name: 'auth', type: 'string', nullable: false },
          { name: 'device_token', type: 'string', nullable: true },
          { name: 'platform', type: 'string', nullable: false },
          { name: 'created_at', type: 'timestamp', nullable: false },
          { name: 'updated_at', type: 'timestamp', nullable: false },
        ],
      },
      {
        name: 'verification_requests',
        columns: [
          { name: 'id', type: 'uuid', nullable: false },
          { name: 'user_id', type: 'uuid', nullable: false },
          { name: 'id_photo_url', type: 'string', nullable: false },
          { name: 'selfie_with_id_url', type: 'string', nullable: false },
          { name: 'status', type: 'string', nullable: false },
          { name: 'rejection_reason', type: 'string', nullable: true },
          { name: 'reviewed_at', type: 'timestamp', nullable: true },
          { name: 'reviewed_by', type: 'string', nullable: true },
          { name: 'created_at', type: 'timestamp', nullable: false },
          { name: 'updated_at', type: 'timestamp', nullable: false },
        ],
      },
      {
        name: 'reports',
        columns: [
          { name: 'id', type: 'uuid', nullable: false },
          { name: 'reporter_id', type: 'uuid', nullable: false },
          { name: 'listing_id', type: 'uuid', nullable: false },
          { name: 'reason', type: 'report_reason', nullable: false },
          { name: 'description', type: 'string', nullable: true },
          { name: 'status', type: 'report_status', nullable: false },
          { name: 'reviewed_at', type: 'timestamp', nullable: true },
          { name: 'reviewed_by', type: 'string', nullable: true },
          { name: 'reviewer_notes', type: 'string', nullable: true },
          { name: 'created_at', type: 'timestamp', nullable: false },
        ],
      },
      {
        name: 'moderation_logs',
        columns: [
          { name: 'id', type: 'uuid', nullable: false },
          { name: 'listing_id', type: 'uuid', nullable: false },
          { name: 'moderator_id', type: 'uuid', nullable: false },
          { name: 'action', type: 'moderation_action', nullable: false },
          { name: 'reason', type: 'string', nullable: true },
          { name: 'ai_flags', type: 'string[]', nullable: true },
          { name: 'ai_confidence_score', type: 'number', nullable: true },
          { name: 'created_at', type: 'timestamp', nullable: false },
        ],
      },
      {
        name: 'broadcast_notifications',
        columns: [
          { name: 'id', type: 'uuid', nullable: false },
          { name: 'admin_id', type: 'uuid', nullable: false },
          { name: 'title', type: 'string', nullable: false },
          { name: 'body', type: 'string', nullable: false },
          { name: 'target_audience', type: 'broadcast_target', nullable: false },
          { name: 'status', type: 'broadcast_status', nullable: false },
          { name: 'sent_count', type: 'number', nullable: false },
          { name: 'failed_count', type: 'number', nullable: false },
          { name: 'scheduled_for', type: 'timestamp', nullable: true },
          { name: 'completed_at', type: 'timestamp', nullable: true },
          { name: 'created_at', type: 'timestamp', nullable: false },
        ],
      },
      {
        name: 'notification_templates',
        columns: [
          { name: 'id', type: 'uuid', nullable: false },
          { name: 'admin_id', type: 'uuid', nullable: false },
          { name: 'name', type: 'string', nullable: false },
          { name: 'title', type: 'string', nullable: false },
          { name: 'body', type: 'string', nullable: false },
          { name: 'target_audience', type: 'string', nullable: false },
          { name: 'created_at', type: 'timestamp', nullable: false },
          { name: 'updated_at', type: 'timestamp', nullable: false },
        ],
      },
      {
        name: 'ai_moderation_results',
        columns: [
          { name: 'id', type: 'uuid', nullable: false },
          { name: 'listing_id', type: 'uuid', nullable: false },
          { name: 'is_flagged', type: 'boolean', nullable: false },
          { name: 'confidence_score', type: 'number', nullable: true },
          { name: 'flags', type: 'string[]', nullable: true },
          { name: 'recommendation', type: 'string', nullable: true },
          { name: 'explanation', type: 'string', nullable: true },
          { name: 'raw_response', type: 'json', nullable: true },
          { name: 'created_at', type: 'timestamp', nullable: false },
        ],
      },
    ],
    views: [
      {
        name: 'public_profiles',
        isView: true,
        columns: [
          { name: 'id', type: 'uuid', nullable: true },
          { name: 'full_name', type: 'string', nullable: true },
          { name: 'username', type: 'string', nullable: true },
          { name: 'avatar_url', type: 'string', nullable: true },
          { name: 'bio', type: 'string', nullable: true },
          { name: 'user_type', type: 'user_type', nullable: true },
          { name: 'business_category', type: 'string', nullable: true },
          { name: 'is_verified', type: 'boolean', nullable: true },
          { name: 'rating_avg', type: 'number', nullable: true },
          { name: 'rating_count', type: 'number', nullable: true },
          { name: 'location_city', type: 'string', nullable: true },
          { name: 'location_state', type: 'string', nullable: true },
          { name: 'website_url', type: 'string', nullable: true },
          { name: 'instagram_url', type: 'string', nullable: true },
          { name: 'whatsapp_number', type: 'string', nullable: true },
          { name: 'created_at', type: 'timestamp', nullable: true },
        ],
      },
      {
        name: 'public_vehicle_attributes',
        isView: true,
        columns: [
          { name: 'id', type: 'uuid', nullable: true },
          { name: 'listing_id', type: 'uuid', nullable: true },
          { name: 'make', type: 'string', nullable: true },
          { name: 'model', type: 'string', nullable: true },
          { name: 'year', type: 'number', nullable: true },
          { name: 'mileage', type: 'number', nullable: true },
          { name: 'fuel_type', type: 'string', nullable: true },
          { name: 'transmission', type: 'string', nullable: true },
          { name: 'color', type: 'string', nullable: true },
          { name: 'condition', type: 'vehicle_condition', nullable: true },
        ],
      },
    ],
    enums: [
      { name: 'app_role', values: ['admin', 'moderator', 'user'] },
      { name: 'broadcast_status', values: ['pending', 'sending', 'completed', 'failed', 'scheduled'] },
      { name: 'broadcast_target', values: ['all', 'sellers', 'buyers', 'verified_users'] },
      { name: 'listing_status', values: ['active', 'sold', 'expired', 'draft', 'pending_review', 'rejected'] },
      { name: 'listing_type', values: ['vehicle', 'part', 'service'] },
      { name: 'message_status', values: ['sent', 'delivered', 'read'] },
      { name: 'message_type', values: ['text', 'image', 'voice'] },
      { name: 'moderation_action', values: ['approved', 'rejected', 'flagged', 'pending'] },
      { name: 'report_reason', values: ['spam', 'inappropriate', 'scam', 'misleading', 'counterfeit', 'other'] },
      { name: 'report_status', values: ['pending', 'reviewed', 'dismissed'] },
      { name: 'service_category', values: ['maintenance', 'bodywork', 'car_wash', 'tires', 'electrical', 'other'] },
      { name: 'user_type', values: ['individual', 'dealer', 'service_provider'] },
      { name: 'vehicle_condition', values: ['new', 'like_new', 'good', 'fair', 'poor'] },
    ],
  };
}
